### ISSUE TITLE
Label hacktoberfest

### ISSUE THREAD

**Issue by n3k00n3** [lampiaosec/virgulino-ruby#21]
We need to add a new label called hacktoberfest.
This way more people could find our project and help it.

**Comment by UserXGnu** [comment]
Where can we add this label? To issues ?

**Comment by n3k00n3** [comment]
Yep, we need to set this new label for each issue.

**Comment by n3k00n3** [comment]
Like that:
https://github.com/Lacsap-/4scanner/issues/43

**Comment by ehx** [comment]
the owner can add this label in : https://github.com/lampiaosec/virgulino-ruby/labels

**Comment by n3k00n3** [comment]
Done! Thanks @ehx
